# Definim compilatorul și opțiunile
CXX = g++
CXXFLAGS = -std=c++17 -Wall

# Fișierul executabil principal
EXEC = Dame101.exe

# Fișiere obiect
OBJS = state.o turn.o main.o

# Testele
TEST_OBJS = test_coord.o test_turn.o
TEST_EXEC = test_suite.exe

# Ținta principală: creare executabilul principal
all: $(EXEC)

# Regulă pentru a lega fișierele obiect într-un executabil principal
$(EXEC): $(OBJS)
	$(CXX) -o $(EXEC) $(OBJS)

# Regulă pentru fiecare fișier obiect
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Regulă pentru compilarea testelor unitare
test: $(TEST_EXEC)

$(TEST_EXEC): $(TEST_OBJS)
	$(CXX) $(CXXFLAGS) -o $(TEST_EXEC) $(TEST_OBJS) -lgtest -lpthread

# Regulă pentru compilarea testului `test_coord.cpp`
test_coord.o: test_coord.cpp
	$(CXX) $(CXXFLAGS) -c test_coord.cpp -o test_coord.o -lgtest

# Regulă pentru compilarea testului `test_turn.cpp`
test_turn.o: test_turn.cpp
	$(CXX) $(CXXFLAGS) -c test_turn.cpp -o test_turn.o -lgtest

# Regulă pentru rularea testelor
runtests: test
	./$(TEST_EXEC)

# Curățare fișiere obiect și executabile
clean:
	rm -f *.o *.exe $(TEST_EXEC)
	rm -f src/*.o tests/*.o
